version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - app_network
    ports:
      - 8000:8000
    expose:
      - 8000

networks:
  app_network:
    name: ecoflight_network
